# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: addba399f033aa326d0bb0becbd5d3c4dcea4a8a7472a2200db9ed9c83751f956489abb0547517ea56a8e7f1e6804b64b2712ae5b0e6f6c59f2e185dbcda65f9

test:
  secret_key_base: d734307bb769c0d593c763e8dc11a7a734f8ddeb4ee567babbd85758fa0fd3969b54f4a57f217fed3540d3cace0d986461667df820515f5bc4753ac08f100ab4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
